plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '1.0.15'
}

version = mod_version
group = mod_group_id

repositories {
    mavenLocal()
}

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = project.neoforge_version

    mods {
        extendedae {
            sourceSet sourceSets.main
        }
    }

    runs {
        client {
            client()
        }
    }

}

repositories {
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
    }
    maven {
        name 'cursemaven'
        url = "https://www.cursemaven.com"
    }
    maven {
        name = "Modmaven"
        url = uri("https://modmaven.dev/")
    }
    mavenCentral()
    flatDir {
        dir "libs"
    }
}

dependencies {
    jarJar(implementation("dev:RecipeSearch:1.3"))
    runtimeOnly "dev.emi:emi-neoforge:1.1.10+1.21"
    runtimeOnly "curse.maven:jade-324717:5427817"

    implementation "curse.maven:polymorph-388800:6794589"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            minecraft_version   : minecraft_version, minecraft_version_range: minecraft_version_range,
            neo_version         : neoforge_version, neo_version_range: neoforge_version_range,
            loader_version_range: loader_version_range,
            mod_id              : mod_id, mod_name: mod_name, mod_version: mod_version,
            mod_authors         : mod_authors,
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}