plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    alias libs.plugins.modDevGradleLegacy
}

version = mod_version

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repositories {
    flatDir {
        dir "libs"
    }

    exclusiveContent {
        forRepository { maven { url = "https://cursemaven.com" } }
        filter { includeGroup("curse.maven") }
    }

    exclusiveContent {
        forRepository { maven { url = "https://maven.terraformersmc.com/releases/" } }
        filter { includeGroup("dev.emi") }
    }

    exclusiveContent {
        forRepository { maven { url = "https://maven.tterrag.com/" } }
        filter { includeGroup("com.tterrag.registrate") }
    }

    maven {
        name = "FirstDarkDev Maven"
        url = "https://maven.firstdark.dev/snapshots"
    }


    maven {
        url "https://maven.shadowsoffire.dev/releases"
        content {
            includeGroup "dev.shadowsoffire"
        }
    }
    maven {
        name = 'GeckoLib'
        url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/'
        content {
            includeGroupByRegex("software\\.bernie.*")
            includeGroup("com.eliotlash.mclib")
        }
    }

    maven {
        name = "Jared's Maven"
        url = "https://maven.blamejared.com/"
    }

    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven {
        url "https://maven.firstdarkdev.xyz/snapshots/"
    }
    maven {
        url "https://maven.quiltmc.org/repository/release/"
    }
    maven {
        url "https://maven.parchmentmc.org"
    }
    maven {
        url "https://maven.architectury.dev/"
    }
    maven {
        url "https://maven.teamresourceful.com/repository/maven-public/"
    }
    maven {
        url "https://maven.jt-dev.tech/releases/"
    }
    maven {
        url "https://mvnrepository.com/artifact/com.hollingsworth.ars_nouveau"
    }
    maven {
        url "https://maven.bawnorton.com/releases"
    }
    maven {
        url "https://maven.enjarai.dev/mirrors"
    }
    maven {
        url "https://maven.twelveiterations.com/repository/maven-public/"
        content {
            includeGroup "net.blay09.mods"
        }
    }
    maven {
        url 'https://dogforce-games.com/maven'
    }
    maven { url = 'https://maven.gtodyssey.com/releases' }
}

dependencies {
    jarJar(implementation 'com.gto.recipesearch:RecipeSearch:26.8.3')
    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'

    modImplementation("dev.shadowsoffire:Placebo:${project.minecraft_version}-8.6.2")
    modImplementation("dev.shadowsoffire:FastSuite:${project.minecraft_version}-5.1.0")

    modImplementation("curse.maven:polymorph-388800:6450982")
    modImplementation("curse.maven:farmers-delight-398521:6154802")

    modImplementation("com.lowdragmc.ldlib:ldlib-forge-${minecraft_version}:1.0.45")

    modImplementation("top.theillusivec4.curios:curios-forge:5.14.1+${project.minecraft_version}")

    modImplementation("vazkii.botania:Botania:${project.minecraft_version}-448-FORGE")
    modImplementation("vazkii.patchouli:Patchouli:${project.minecraft_version}-84.1-FORGE")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    parchment {
        minecraftVersion = parchment_minecraft_version
        mappingsVersion = parchment_mappings_version
    }

    runs {
        client {
            client()
            gameDirectory.set(file('run/client'))
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')
}


base {
    archivesName = mod_id
}

afterEvaluate {
    tasks.withType(org.gradle.jvm.tasks.Jar).configureEach {
        manifest.attributes([
                'MixinConfigs': "${mod_id}.mixins.json",
                'Specification-Title': project.name,
                'Specification-Version': mod_version,
                'Implementation-Title': base.archivesName,
                'Implementation-Version': version,
                'Name': 'fast/fastrecipesearch/mixin',
                'Sealed': 'true'
        ])
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            version                 : version,
            mod_id                  : mod_id,
            mod_license             : mod_license,
            mod_name                : mod_name,
            mod_description         : mod_description,
            mod_url                 : mod_url,
            mod_issue_tracker       : mod_issue_tracker
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
legacyForge.ideSyncTask generateModMetadata
