plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    alias libs.plugins.modDevGradleLegacy
}

version = mod_version

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

repositories {
    flatDir {
        dir "libs"
    }

    exclusiveContent {
        forRepository { maven { url = "https://cursemaven.com" } }
        filter { includeGroup("curse.maven") }
    }
}

dependencies {
    jarJar(implementation("dev:RecipeSearch:1.0"))
    annotationProcessor 'org.spongepowered:mixin:0.8.7:processor'

    modImplementation("curse.maven:create-328085:7178761")

    modImplementation("curse.maven:applied-energistics-2-223794:7148487")

    modImplementation("curse.maven:mekanism-268560:6552911")
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"
    config "${mod_id}.mixins.json"
}

legacyForge {
    version = "${minecraft_version}-${forge_version}"

    parchment {
        minecraftVersion = parchment_minecraft_version
        mappingsVersion = parchment_mappings_version
    }

    runs {
        client {
            client()
            gameDirectory.set(file('run/client'))
            systemProperty 'neoforge.enabledGameTestNamespaces', project.mod_id
        }
    }

    mods {
        "${mod_id}" {
            sourceSet(sourceSets.main)
        }
    }

    accessTransformers = project.files('src/main/resources/META-INF/accesstransformer.cfg')
}


base {
    archivesName = mod_id
}

afterEvaluate {
    tasks.withType(org.gradle.jvm.tasks.Jar).configureEach {
        manifest.attributes([
                'MixinConfigs': "${mod_id}.mixins.json",
                'Specification-Title': project.name,
                'Specification-Version': mod_version,
                'Implementation-Title': base.archivesName,
                'Implementation-Version': version,
                'Name': 'fast/fastrecipesearch/mixin',
                'Sealed': 'true'
        ])
    }
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            version                 : version,
            mod_id                  : mod_id,
            mod_license             : mod_license,
            mod_name                : mod_name,
            mod_description         : mod_description,
            mod_url                 : mod_url,
            mod_issue_tracker       : mod_issue_tracker
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}
sourceSets.main.resources.srcDir generateModMetadata
legacyForge.ideSyncTask generateModMetadata
