org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

minecraft_release=1.21.1
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,)
neoforge_version=21.1.113
neoforge_version_range=[21.1.113,)
loader_version_range=[1,)

mod_id=fastrecipesearch
mod_name=Fast Recipe Search
mod_version=1.21.1-26.2-neoforge
mod_group_id=fast
mod_authors=nutant233
