org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=false

parchment_minecraft_version=1.20.1
parchment_mappings_version=2023.09.03
minecraft_version=1.20.1
forge_version=47.4.9

mod_version=1.20.1-1.4-forge
mod_id=fastrecipesearch
mod_name=Fast Recipe Search
mod_url=https://github.com/nutant233/Fast-Recipe-Search/
mod_description=Significantly speed up recipe search.
mod_issue_tracker=https://github.com/nutant233/Fast-Recipe-Search/issues/
mod_license=LGPL-3.0