pluginManagement {
    repositories {
        mavenLocal()
        gradlePluginPortal()
        maven { url = "https://maven.neoforged.net/releases"}
        maven { url = "https://maven.minecraftforge.net/" }
    }
}

dependencyResolutionManagement {
    versionCatalogs {
        libs {
            version("modDevGradleLegacy", "2.0.116")

            plugin("modDevGradleLegacy", "net.neoforged.moddev.legacyforge").versionRef("modDevGradleLegacy")
        }
    }
}

rootProject.name = mod_id