modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPL-3.0"
[[mods]]
modId="fastrecipesearch"
issueTrackerURL="https://github.com/nutant233/Fast-Recipe-Search/issues"
displayURL="https://github.com/nutant233/Fast-Recipe-Search"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"

[[mixins]]
config="fastrecipesearch.mixins.json"